#cloud-config

package_upgrade: true

runcmd:
  - apt update
  - apt install -y apt-transport-https ca-certificates curl software-properties-common  
  #- add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
  #- apt update
  #- apt-cache policy docker-ce
  #- apt install -y docker-ce
  #- curl -L https://github.com/docker/compose/releases/download/1.24.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
  #- chmod +x /usr/local/bin/docker-compose
  - apt install -y xfce4 xfce4-whiskermenu-plugin xfce4-terminal thunar-archive-plugin gedit unzip
  - apt install -y x2goserver x2goserver-xsession
  - apt install -y openjdk-8-jdk
  - sed -i -e '/^assistive_technologies=/s/^/#/' /etc/java-*-openjdk/accessibility.properties
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - cd /home/ubuntu/
  - wget http://www.pirbot.com/mirrors/apache//jmeter/binaries/apache-jmeter-5.1.1.zip
  - unzip apache-jmeter-5.1.1.zip
  - chown -R ubuntu:ubuntu apache-jmeter-5.1.1
  #- adduser --disabled-password --gecos "" appuser
  #- usermod -aG docker appuser
  #- mkdir -p /data
  #- chown -R appuser:appuser /data

power_state:
  delay: "now"
  mode: reboot
  message: First reboot
  condition: True
